"""initial_schema

Revision ID: 9e2a8684f1a2
Revises: 
Create Date: 2026-03-15 18:11:43.964316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2a8684f1a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('inverter_type', sa.String(), nullable=False),
    sa.Column('capacity_kw', sa.Float(), nullable=False),
    sa.Column('grid_zone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('household_id')
    )
    op.create_table('energy_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('daily_generation_kwh', sa.Float(), nullable=True),
    sa.Column('daily_consumption_kwh', sa.Float(), nullable=True),
    sa.Column('grid_import_kwh', sa.Float(), nullable=True),
    sa.Column('grid_export_kwh', sa.Float(), nullable=True),
    sa.Column('carbon_offset_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.household_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_energy_reports_date'), 'energy_reports', ['date'], unique=False)
    op.create_table('inverter_devices',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.household_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('user_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('inverter_token', sa.String(), nullable=True),
    sa.Column('jwt_refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.household_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_table('inverter_devices')
    op.drop_index(op.f('ix_energy_reports_date'), table_name='energy_reports')
    op.drop_table('energy_reports')
    op.drop_table('households')
    # ### end Alembic commands ###
